// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using SecondHandTradePlatfrom.Models;
using System;

namespace SecondHandTradePlatfrom.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("SecondHandTradePlatfrom.Models.Account", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("phoneNumber")
                        .IsRequired();

                    b.Property<int>("sex");

                    b.HasKey("userId");

                    b.HasIndex("name");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SecondHandTradePlatfrom.Models.School", b =>
                {
                    b.Property<string>("name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("name");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("SecondHandTradePlatfrom.Models.Account", b =>
                {
                    b.HasOne("SecondHandTradePlatfrom.Models.School", "school")
                        .WithMany("accounts")
                        .HasForeignKey("name")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
